query getUser {
  user {
    firstName
    lastName
    email
    role
    avatarColor
    meta {
      plant {
        id
        code
        name
      }
      company {
        id
        name
      }
    }
  }
}
